apiVersion: v1
kind: ServiceAccount
metadata:
  name: virtualization-controller
  namespace: kubesphere-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualization-controller
rules:
  - apiGroups: ["virtualization.kubesphere.io"]
    resources: ["virtualmachines", "virtualmachines/status", "virtualmachines/finalizers", "virtualdisks", "virtualnets", "vmsnapshots", "vmtemplates"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["snapshot.storage.k8s.io"]
    resources: ["volumesnapshots", "volumesnapshotcontents"]
    verbs: ["*"]
  - apiGroups: ["kubevirt.io"]
    resources: ["virtualmachines", "virtualmachineinstances"]
    verbs: ["*"]
  - apiGroups: ["cdi.kubevirt.io"]
    resources: ["datavolumes"]
    verbs: ["*"]
  - apiGroups: ["k8s.cni.cncf.io"]
    resources: ["network-attachment-definitions"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events", "pods", "secrets", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: virtualization-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: virtualization-controller
subjects:
  - kind: ServiceAccount
    name: virtualization-controller
    namespace: kubesphere-system
