apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vmsnapshots.virtualization.kubesphere.io
spec:
  group: virtualization.kubesphere.io
  names:
    kind: VMSnapshot
    listKind: VMSnapshotList
    plural: vmsnapshots
    singular: vmsnapshot
    shortNames:
      - vmsnap
      - vmsnaps
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [sourceRef]
              properties:
                sourceRef:
                  type: object
                  required: [namespace, name]
                  properties:
                    namespace:
                      type: string
                      minLength: 1
                    name:
                      type: string
                      minLength: 1
                includedDisks:
                  type: array
                  items:
                    type: string
                retainPolicy:
                  type: string
                  enum: [Retain, Delete]
                  default: Retain
            status:
              type: object
              properties:
                readyToUse:
                  type: boolean
                conditions:
                  type: array
                  items:
                    type: object
      subresources:
        status: {}
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [sourceRef]
              properties:
                sourceRef:
                  type: object
                  required: [namespace, name]
                  properties:
                    namespace:
                      type: string
                      minLength: 1
                    name:
                      type: string
                      minLength: 1
                includedDisks:
                  type: array
                  items:
                    type: string
                retainPolicy:
                  type: string
                  enum: [Retain, Delete]
                  default: Retain
            status:
              type: object
              properties:
                readyToUse:
                  type: boolean
                conditions:
                  type: array
                  items:
                    type: object
      subresources:
        status: {}
