apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: virtualmachines.virtualization.kubesphere.io
spec:
  group: virtualization.kubesphere.io
  names:
    kind: VirtualMachine
    listKind: VirtualMachineList
    plural: virtualmachines
    singular: virtualmachine
    shortNames:
      - vm
      - vms
  scope: Namespaced
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: virtualization-webhook-service
          namespace: kubesphere-system
          path: /convert
      conversionReviewVersions:
        - v1
  versions:
    - name: v1alpha1
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [cpu, memory, disks, nets]
              properties:
                cpu:
                  type: string
                  pattern: '^([1-9][0-9]*|[0-9]+m)$'
                memory:
                  type: string
                  pattern: '^([1-9][0-9]*|[0-9]+)(Mi|Gi)$'
                cpuModel:
                  type: string
                  pattern: '^[A-Za-z0-9_.-]+$'
                dedicatedCPUPlacement:
                  type: boolean
                  default: false
                numa:
                  type: object
                  properties:
                    cells:
                      type: array
                      minItems: 1
                      items:
                        type: object
                        required:
                          - id
                          - cpus
                          - memory
                        properties:
                          id:
                            type: integer
                            minimum: 0
                          cpus:
                            type: string
                            pattern: '^[0-9]+(-[0-9]+)?(,[0-9]+(-[0-9]+)?)*$'
                          memory:
                            type: string
                            pattern: '^([1-9][0-9]*)(Mi|Gi)$'
                          threadsPerCore:
                            type: integer
                            minimum: 1
                numaPolicy:
                  type: string
                  default: none
                  enum: [none, strict, best-effort]
                hugepages:
                  type: string
                  enum: ["", "1Gi", "2Mi"]
                  default: ""
                gpus:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - deviceType
                      - resourceName
                    properties:
                      name:
                        type: string
                        minLength: 1
                      deviceType:
                        type: string
                        enum: [vgpu, passthrough]
                      resourceName:
                        type: string
                        pattern: '^[a-z0-9.-]+/[a-z0-9.-]+$'
                disks:
                  type: array
                  minItems: 1
                  items:
                    type: object
                    required: [type, diskRef]
                    properties:
                      type:
                        type: string
                        enum: [system, data, ephemeral]
                      bus:
                        type: string
                        enum: [virtio, sata, scsi]
                        default: virtio
                      cache:
                        type: string
                        enum: [none, writeback, writethrough, directsync]
                        default: none
                      iothread:
                        type: boolean
                        default: false
                      bootOrder:
                        type: integer
                        minimum: 1
                      hotplug:
                        type: boolean
                        default: false
                      diskRef:
                        type: object
                        required: [name]
                        properties:
                          name:
                            type: string
                            minLength: 1
                nets:
                  type: array
                  minItems: 1
                  items:
                    type: object
                    required: [type]
                    properties:
                      type:
                        type: string
                        enum: [bridge, masquerade, sriov]
                      nadRef:
                        type: object
                        required: [namespace, name]
                        properties:
                          namespace:
                            type: string
                            minLength: 1
                          name:
                            type: string
                            minLength: 1
                      model:
                        type: string
                        pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
                      bandwidth:
                        type: string
                        pattern: '^([0-9]+)(K|M|G)?bps$'
                      sriovResource:
                        type: string
                      multiqueue:
                        type: boolean
                        default: false
                cloudInit:
                  type: object
                  properties:
                    userData:
                      type: string
                    networkData:
                      type: string
                    sshAuthorizedKeys:
                      type: array
                      items:
                        type: string
                    userDataSecretRef:
                      type: object
                      required: [namespace, name]
                      properties:
                        namespace:
                          type: string
                          minLength: 1
                        name:
                          type: string
                          minLength: 1
                    networkDataSecretRef:
                      type: object
                      required: [namespace, name]
                      properties:
                        namespace:
                          type: string
                          minLength: 1
                        name:
                          type: string
                          minLength: 1
                console:
                  type: object
                  properties:
                    vnc:
                      type: boolean
                      default: true
                    serial:
                      type: boolean
                      default: true
                    type:
                      type: string
                      enum: ["", "spice"]
                liveMigration:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      default: false
                    bandwidth:
                      type: string
                      pattern: '^([1-9][0-9]*)(Mi|Gi)$'
                    completionTimeoutSeconds:
                      type: integer
                      minimum: 0
                    allowPostCopy:
                      type: boolean
                      default: false
                    autoConverge:
                      type: boolean
                      default: false
                livenessProbe:
                  type: object
                  properties:
                    periodSeconds:
                      type: integer
                      minimum: 1
                      default: 10
                    timeoutSeconds:
                      type: integer
                      minimum: 1
                      default: 30
                    failureThreshold:
                      type: integer
                      minimum: 1
                      default: 3
                readinessProbe:
                  type: object
                  properties:
                    periodSeconds:
                      type: integer
                      minimum: 1
                      default: 10
                    timeoutSeconds:
                      type: integer
                      minimum: 1
                      default: 30
                    failureThreshold:
                      type: integer
                      minimum: 1
                      default: 3
                powerState:
                  type: string
                  enum: [Running, Stopped]
                kubeVirt:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  default: Running
            status:
              type: object
              properties:
                powerState:
                  type: string
                  enum: [Running, Stopped]
                phase:
                  type: string
                migrationState:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    required: [type, status, lastTransitionTime, reason, message]
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                        enum: ["True", "False", "Unknown"]
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string
      additionalPrinterColumns:
        - name: Power
          type: string
          jsonPath: .status.powerState
        - name: CPU
          type: string
          jsonPath: .spec.cpu
        - name: Memory
          type: string
          jsonPath: .spec.memory
    - name: v1beta1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [cpu, memory, disks, nets]
              properties:
                cpu:
                  type: string
                  pattern: '^([1-9][0-9]*|[0-9]+m)$'
                memory:
                  type: string
                  pattern: '^([1-9][0-9]*|[0-9]+)(Mi|Gi)$'
                cpuModel:
                  type: string
                  pattern: '^[A-Za-z0-9_.-]+$'
                dedicatedCPUPlacement:
                  type: boolean
                  default: false
                numaPolicy:
                  type: string
                  default: none
                  enum: [none, strict, best-effort]
                numa:
                  type: object
                  properties:
                    cells:
                      type: array
                      minItems: 1
                      items:
                        type: object
                        required:
                          - id
                          - cpus
                          - memory
                        properties:
                          id:
                            type: integer
                            minimum: 0
                          cpus:
                            type: string
                            pattern: '^[0-9]+(-[0-9]+)?(,[0-9]+(-[0-9]+)?)*$'
                          memory:
                            type: string
                            pattern: '^([1-9][0-9]*)(Mi|Gi)$'
                          threadsPerCore:
                            type: integer
                            minimum: 1
                hugepages:
                  type: string
                  enum: ["", "1Gi", "2Mi"]
                gpus:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                      - deviceType
                      - resourceName
                    properties:
                      name:
                        type: string
                        minLength: 1
                      deviceType:
                        type: string
                        enum: [vgpu, passthrough]
                      resourceName:
                        type: string
                        pattern: '^[a-z0-9.-]+/[a-z0-9.-]+$'
                disks:
                  type: array
                  items:
                    type: object
                    required: [type, diskRef]
                    properties:
                      type:
                        type: string
                        enum: [system, data, ephemeral]
                      bus:
                        type: string
                        enum: [virtio, sata, scsi]
                        default: virtio
                      cache:
                        type: string
                        enum: [none, writeback, writethrough, directsync]
                        default: none
                      iothread:
                        type: boolean
                        default: false
                      bootOrder:
                        type: integer
                        minimum: 1
                      hotplug:
                        type: boolean
                        default: false
                      diskRef:
                        type: object
                        required: [name]
                        properties:
                          name:
                            type: string
                            minLength: 1
                nets:
                  type: array
                  items:
                    type: object
                    required: [type]
                    properties:
                      type:
                        type: string
                        enum: [bridge, masquerade, sriov]
                      nadRef:
                        type: object
                        required: [namespace, name]
                        properties:
                          namespace:
                            type: string
                            minLength: 1
                          name:
                            type: string
                            minLength: 1
                      model:
                        type: string
                        pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
                      bandwidth:
                        type: string
                        pattern: '^([0-9]+)(K|M|G)?bps$'
                      sriovResource:
                        type: string
                      multiqueue:
                        type: boolean
                        default: false
                cloudInit:
                  type: object
                  properties:
                    userData:
                      type: string
                    networkData:
                      type: string
                    sshAuthorizedKeys:
                      type: array
                      items:
                        type: string
                    userDataSecretRef:
                      type: object
                      required: [namespace, name]
                      properties:
                        namespace:
                          type: string
                          minLength: 1
                        name:
                          type: string
                          minLength: 1
                    networkDataSecretRef:
                      type: object
                      required: [namespace, name]
                      properties:
                        namespace:
                          type: string
                          minLength: 1
                        name:
                          type: string
                          minLength: 1
                console:
                  type: object
                  properties:
                    vnc:
                      type: boolean
                      default: true
                    serial:
                      type: boolean
                      default: true
                    type:
                      type: string
                      enum: ["", "spice"]
                liveMigration:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      default: false
                    bandwidth:
                      type: string
                      pattern: '^([1-9][0-9]*)(Mi|Gi)$'
                    completionTimeoutSeconds:
                      type: integer
                      minimum: 0
                    allowPostCopy:
                      type: boolean
                      default: false
                    autoConverge:
                      type: boolean
                      default: false
                livenessProbe:
                  type: object
                  properties:
                    periodSeconds:
                      type: integer
                    timeoutSeconds:
                      type: integer
                    failureThreshold:
                      type: integer
                readinessProbe:
                  type: object
                  properties:
                    periodSeconds:
                      type: integer
                    timeoutSeconds:
                      type: integer
                    failureThreshold:
                      type: integer
                powerState:
                  type: string
                  enum: [Running, Stopped]
                kubeVirt:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties:
                powerState:
                  type: string
                  enum: [Running, Stopped]
                phase:
                  type: string
                migrationState:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      lastTransitionTime:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
      subresources:
        status: {}
